#!/bin/sh

######## Main script for the main program: cross section calculations at N3LO in QCD ########

maindir=$(pwd)

# Parameters read from the command-line:
#   lattice size
#   seed for the pseudo-random-number generator 
#   optional flag --scale or --7point; if absent, the renormalization scale is set equal to mu_F (see dy_parameters.in)
#            --scale: This generates 16 predictions for various renormalization scales muR between 0.5*muR0 and 2.0*muR0
#            --7point: This calculates the 7-point scale uncertainty of the cross section

default=0

if [ "$#" -gt 5 ]; then
    echo "You cannot use more than three arguments"
    exit
fi
if [ "$#" -lt 4 ]; then
    if [ "$#" -eq 0 ]
    then
	default=1
    elif [ $1 == "-h" ] || [ $1 == "--help" ]
    then
	echo ""
	echo "## User help for n3loxs program that calculates various hadronic cross sections up to N3LO in QCD ##"
	echo "Usage: ./n3loxs -lattice a -seed b (--scale/--7point) with:"
	echo "a: Lattice size (integer)"
	echo "b: Seed for the pseudo-random-number generator (integer)"
	echo "Optional flag --scale or --7point; if absent, the renormalization scale is set equal to mu_F (see dy_parameters.in)"
	echo "   --scale: generate 16 predictions for mu_R varied between 0.5*mu_0 and 2*mu_0, mu_0 is the central renormalization scale"
	echo "   --7point: calculate the 7-point scale uncertainty of the cross sexction"
	echo ""
	exit
    else
	echo "You must enter at least two parameters"
	exit
    fi
fi

if [[ ( $default -eq 0 ) && ( $1 != "-lattice" || $3 != "-seed" ) ]]
then
    echo "Mis-typed entries on the command-line, the program will exit..."
    exit
fi

if [[ $default -eq 0 ]]
then
    lattice=$2
    seed=$4
    seven=0
else
    lattice=1000
    seed=1
    seven=0
fi

if [[ "$#" -eq 5 ]]
then
    if [ $5 == "--scale" ]
    then
	scale=$5
	seven=0
    elif [ $5 == "--7point" ]
    then
	scale="--scale"
	seven=1
    else
	echo "The optional flag is mistyped, the program will exit..."
	exit
    fi
else
    scale=
fi


# Now read the input parameters from the input file dy_parameters.in
inputfile="./n3loxs_parameters.in";
while read p1 p2 p3
do
    if [[ $p1 == "channel" && $p2 == "=" ]]
    then
	type=$p3
    elif [[ $p1 == "PDFset" && $p2 == "=" ]]
    then
	pdfset=$p3
    elif [[ $p1 == "PDFnum" && $p2 == "=" ]]
    then
	pdfnum=$p3
    elif [[ $p1 == "order" && $p2 == "=" ]]
    then
	qcd=$p3
    elif [[ $p1 == "collider" && $p2 == "=" ]]
    then
	collider=$p3
    elif [[ $p1 == "energy" && $p2 == "=" ]]
    then
	energy=$p3
    elif [[ $p1 == "Q" && $p2 == "=" ]]
    then
	q=$p3
    elif [[ $p1 == "muf_flag" && $p2 == "=" ]]
    then
	muf_flag=$p3
    elif [[ $p1 == "muf0" && $p2 == "=" ]]
    then
	muf0=$p3
    elif [[ $p1 == "xmuf" && $p2 == "=" ]]
    then
	xmuf=$p3
    elif [[ $p1 == "mur_flag" && $p2 == "=" ]]
    then
	mur_flag=$p3
    elif [[ $p1 == "mur0" && $p2 == "=" ]]
    then
	mur0=$p3
    elif [[ $p1 == "xmur" && $p2 == "=" ]]
    then
	xmur=$p3
    fi

    if [[ $p1 == "MW" && $p2 == "=" ]]
    then
	mw=$p3
    elif [[ $p1 == "GammaW" && $p2 == "=" ]]
    then
	width_w=$p3
    elif [[ $p1 == "MZ" && $p2 == "=" ]]
    then
	mz=$p3
    elif [[ $p1 == "MH" && $p2 == "=" ]]
    then
	mh=$p3
    elif [[ $p1 == "Mt" && $p2 == "=" ]]
    then
	mt=$p3
    elif [[ $p1 == "Mb" && $p2 == "=" ]]
    then
	mb=$p3
    elif [[ $p1 == "mt(mt)" && $p2 == "=" ]]
    then
	mtmt=$p3
    elif [[ $p1 == "mb(mb)" && $p2 == "=" ]]
    then
	mbmb=$p3
    elif [[ $p1 == "vev" && $p2 == "=" ]]
    then
	vev=$p3
    elif [[ $p1 == "1/alpha" && $p2 == "=" ]]
    then
	alphainv=$p3
    elif [[ $p1 == "mt_scheme" && $p2 == "=" ]]
    then
	mtscheme=$p3
    fi

done < $inputfile

if [ $type -eq 1 ]
then
    parameters="$mz $alphainv"
elif [[ $type -eq 2 || $type -eq 3 ]]
then
    parameters="$mw $mz $vev"
elif [[ $type -eq 4 || $type -eq 5 ]]
then
    parameters="$mw $mz $mh $vev"
elif [ $type -eq 6 ]
then
    parameters="$mz $mh $mb $mbmb $vev"
elif [ $type -eq 7 ]
then
    if [ $mtscheme -eq 0 ]
    then
	parameters="$mz $mh $mt $vev $mtscheme"
    else
	parameters="$mz $mh $mtmt $vev $mtscheme"
    fi
fi

if [ -z ${muf0} ]; then muf0=100.0; fi
if [ -z ${mur0} ]; then mur0=100.0; fi

echo ""
echo ""
echo "\t################  n3loxs v1.0 calculator ################"
echo "\t######### Input parameters for the calculation: #########"
if [ $collider -eq 0 ]
then
    echo "\t  p-p collider at a c.o.m. energy sqrt(s) = $energy TeV"
else
    echo "\t  p-pbar collider at a c.o.m. energy sqrt(s) = $energy TeV"
fi
if [ $qcd -eq 0 ]
then
    qcdw=LO
elif [ $qcd -eq 1 ]
then
    qcdw=NLO
elif [ $qcd -eq 2 ]
then
    qcdw=NNLO
else
    qcdw=N3LO
fi
echo "\t  Maximum QCD order of the calculation: $qcdw"
echo "\t  PDF set:                              $pdfset"
echo "\t  PDF member:                           $pdfnum"
echo "\t  W boson mass MW:                      $mw GeV"
echo "\t  Z boson mass MZ:                      $mz GeV"
echo "\t  Higgs boson mass MH:                  $mh GeV"
echo "\t  Top-quark pole mass Mt:               $mt GeV"
echo "\t  Bottom-quark pole mass Mb:            $mb GeV"
echo "\t  Top-quark MSbar mass mt(mt):          $mtmt GeV"
echo "\t  Bottom-quark MSbar mass mb(mb):       $mbmb GeV"
echo "\t  Vacuum expectation value vev:         $vev GeV"
echo "\t  1/alpha EM constant:                  $alphainv"

if [ $type -lt 3 ]
then
    echo "\t  Off-shell Q-value Q = ${q} GeV"
fi


if [ $type -eq 1 ]; then
    # Drell-Yan p p(pbar) --> gamma* + X --> l+ l- + X
    proctag=dy_xs_gamma
    if [ $seven -eq 0 ]
    then
	if [ $muf_flag == 0 ]
	then
	    echo "\t  Factorization scale muF = $xmuf * Q\n"
	else
	    echo "\t  Factorization scale muF = $xmuf * $muf0 GeV\n"
	fi
	if [ -z ${scale} ]
	then
	    if [ $mur_flag == 0 ]
	    then
		echo "\t  Renormalization scale muR = $xmur * Q\n"
	    else
		echo "\t  Renormalization scale muR = $xmur * $mur0 GeV\n"
	    fi
	fi
    else
	if [ $muf_flag == 0 ]
	then
	    if [ $mur_flag == 0 ]
	    then
		echo "\t  Central scales muF0 = muR0 = Q\n"
	    else
		echo "\t  Central scales muF0 = Q, muR0 = $mur0 GeV\n"
	    fi
	else
	    if [ $mur_flag == 0 ]
	    then
		echo "\t  Central scales muF0 = $muf0 GeV, muR0 = Q\n"
	    else
		echo "\t  Central scales muF0 = $muf0 GeV, muR0 = $mur0 GeV\n"
	    fi
	fi
    fi
    echo "\tNow calculating for neutral Drell-Yan process...\n"
    if [ $seven -eq 0 ]
    then
	${maindir}/subprogs/run_dy_phot $lattice $seed $qcd $collider $energy $q $xmuf $muf0 $xmur $mur0 $muf_flag $mur_flag $pdfset $pdfnum $parameters $scale
    else
	${maindir}/subprogs/run_dy_phot $lattice $seed $qcd $collider $energy $q 1.0 $muf0 $xmur $mur0 $muf_flag $mur_flag $pdfset $pdfnum $parameters --scale
	${maindir}/subprogs/run_dy_phot $lattice $seed $qcd $collider $energy $q 0.5 $muf0 $xmur $mur0 $muf_flag $mur_flag $pdfset $pdfnum $parameters --scale
	${maindir}/subprogs/run_dy_phot $lattice $seed $qcd $collider $energy $q 2.0 $muf0 $xmur $mur0 $muf_flag $mur_flag $pdfset $pdfnum $parameters --scale
    fi
elif [[ $type -eq 2 || $type -eq 3 ]]; then
    # Drell-Yan p p(pbar) --> W+ + X --> l+ nu_l + X / W- + X --> l- ~nu_l + X
    if [ $seven -eq 0 ]
    then
	if [ $muf_flag == 0 ]
	then
	    echo "\t  Factorization scale muF = $xmuf * Q\n"
	else
	    echo "\t  Factorization scale muF = $xmuf * $muf0 GeV\n"
	fi
	if [ -z ${scale} ]
	then
	    if [ $mur_flag == 0 ]
	    then
		echo "\t  Renormalization scale muR = $xmur * Q\n"
	    else
		echo "\t  Renormalization scale muR = $xmur * $mur0 GeV\n"
	    fi
	fi
    else
	if [ $muf_flag == 0 ]
	then
	    if [ $mur_flag == 0 ]
	    then
		echo "\t  Central scales muF0 = muR0 = Q\n"
	    else
		echo "\t  Central scales muF0 = Q, muR0 = $mur0 GeV\n"
	    fi
	else
	    if [ $mur_flag == 0 ]
	    then
		echo "\t  Central scales muF0 = $muf0 GeV, muR0 = Q\n"
	    else
		echo "\t  Central scales muF0 = $muf0 GeV, muR0 = $mur0 GeV\n"
	    fi
	fi
    fi
    if [ $type -eq 2 ]
    then
	echo "\tNow calculating for charged W+ Drell-Yan process...\n"
	wtype=1
	proctag=dy_xs_wplus
    else
	echo "\tNow calculating for charged W- Drell-Yan process...\n"
	wtype=-1
	proctag=dy_xs_wminus
    fi
    if [ $seven -eq 0 ]
    then
	${maindir}/subprogs/run_dy_w $lattice $seed $qcd $collider $energy $q $wtype $xmuf $muf0 $xmur $mur0 $muf_flag $mur_flag $pdfset $pdfnum $parameters $scale
    else
	${maindir}/subprogs/run_dy_w $lattice $seed $qcd $collider $energy $q $wtype 1.0 $muf0 $xmur $mur0 $muf_flag $mur_flag $pdfset $pdfnum $parameters --scale
	${maindir}/subprogs/run_dy_w $lattice $seed $qcd $collider $energy $q $wtype 0.5 $muf0 $xmur $mur0 $muf_flag $mur_flag $pdfset $pdfnum $parameters --scale
	${maindir}/subprogs/run_dy_w $lattice $seed $qcd $collider $energy $q $wtype 2.0 $muf0 $xmur $mur0 $muf_flag $mur_flag $pdfset $pdfnum $parameters --scale
    fi
elif [[ $type -eq 4 || $type -eq 5 ]]; then
    # Higgs-strahlung p p(pbar) --> W+ H / W- H + X
    if [ $seven -eq 0 ]
    then
	if [ $muf_flag == 0 ]
	then
	    echo "\t  Factorization scale muF = $xmuf * (MW + MH)\n"
	else
	    echo "\t  Factorization scale muF = $xmuf * $muf0 GeV\n"
	fi
	if [ -z ${scale} ]
	then
	    if [ $mur_flag == 0 ]
	    then
		echo "\t  Renormalization scale muR = $xmur * (MW + MH)\n"
	    else
		echo "\t  Renormalization scale muR = $xmur * $mur0 GeV\n"
	    fi
	fi
    else
	if [ $muf_flag == 0 ]
	then
	    if [ $mur_flag == 0 ]
	    then
		echo "\t  Central scales muF0 = muR0 = MW + MH\n"
	    else
		echo "\t  Central scales muF0 = MW + MH, muR0 = $mur0 GeV\n"
	    fi
	else
	    if [ $mur_flag == 0 ]
	    then
		echo "\t  Central scales muF0 = $muf0 GeV, muR0 = MW + MH\n"
	    else
		echo "\t  Central scales muF0 = $muf0 GeV, muR0 = $mur0 GeV\n"
	    fi
	fi
    fi
    if [ $type -eq 4 ]
    then
	echo "\tNow calculating for inclusive Higgs-strahlung W+ H process...\n"
	wtype=1
	proctag=WplusH_xs
    else
	echo "\tNow calculating for inclusive Higgs-strahlung W- H process...\n"
	wtype=-1
	proctag=WminusH_xs
    fi
    if [ $seven -eq 0 ]
    then
	${maindir}/subprogs/run_wh $lattice $seed $qcd $collider $energy $wtype $xmuf $muf0 $xmur $mur0 $muf_flag $mur_flag $pdfset $pdfnum $parameters $scale
    else
	${maindir}/subprogs/run_wh $lattice $seed $qcd $collider $energy $wtype 1.0 $muf0 $xmur $mur0 $muf_flag $mur_flag $pdfset $pdfnum $parameters --scale
	${maindir}/subprogs/run_wh $lattice $seed $qcd $collider $energy $wtype 0.5 $muf0 $xmur $mur0 $muf_flag $mur_flag $pdfset $pdfnum $parameters --scale
	${maindir}/subprogs/run_wh $lattice $seed $qcd $collider $energy $wtype 2.0 $muf0 $xmur $mur0 $muf_flag $mur_flag $pdfset $pdfnum $parameters --scale
    fi
elif [ $type -eq 6 ]; then
    # Bottom-quark fusion p p(pbar) --> H + X via b bbar --> H
    proctag=bbH_xs
    if [ $seven -eq 0 ]
    then
	if [ $muf_flag == 0 ]
	then
	    echo "\t  Factorization scale muF = $xmuf * (MH+2*mb_pole)/4\n"
	else
	    echo "\t  Factorization scale muF = $xmuf * $muf0 GeV\n"
	fi
	if [ -z ${scale} ]
	then
	    if [ $mur_flag == 0 ]
	    then
		echo "\t  Renormalization scale muR = $xmur * MH\n"
	    else
		echo "\t  Renormalization scale muR = $xmur * $mur0 GeV\n"
	    fi
	fi
    else
	if [ $muf_flag == 0 ]
	then
	    if [ $mur_flag == 0 ]
	    then
		echo "\t  Central scales muF0 = (MH+2*mb_pole)/4, muR0 = MH\n"
	    else
		echo "\t  Central scales muF0 = (MH+2*mb_pole)/4, muR0 = $mur0 GeV\n"
	    fi
	else
	    if [ $mur_flag == 0 ]
	    then
		echo "\t  Central scales muF0 = $muf0 GeV, muR0 = MH\n"
	    else
		echo "\t  Central scales muF0 = $muf0 GeV, muR0 = $mur0 GeV\n"
	    fi
	fi
    fi
    echo "\tNow calculating for inclusive 5FS bbH process...\n"
    if [ $seven -eq 0 ]
    then
	${maindir}/subprogs/run_bbh $lattice $seed $qcd $collider $energy $xmuf $muf0 $xmur $mur0 $muf_flag $mur_flag $pdfset $pdfnum $parameters $scale
    else
	${maindir}/subprogs/run_bbh $lattice $seed $qcd $collider $energy 1.0 $muf0 $xmur $mur0 $muf_flag $mur_flag $pdfset $pdfnum $parameters --scale
	${maindir}/subprogs/run_bbh $lattice $seed $qcd $collider $energy 0.5 $muf0 $xmur $mur0 $muf_flag $mur_flag $pdfset $pdfnum $parameters --scale
	${maindir}/subprogs/run_bbh $lattice $seed $qcd $collider $energy 2.0 $muf0 $xmur $mur0 $muf_flag $mur_flag $pdfset $pdfnum $parameters --scale
    fi
elif [ $type -eq 7 ]; then
    # Gluon fusion p p(pbar) --> H + X via g g --> H
    proctag=ggH_xs
    if [ $seven -eq 0 ]
    then
	if [ $muf_flag == 0 ]
	then
	    echo "\t  Factorization scale muF = $xmuf * MH/2\n"
	else
	    echo "\t  Factorization scale muF = $xmuf * $muf0 GeV\n"
	fi
	if [ -z ${scale} ]
	then
	    if [ $mur_flag == 0 ]
	    then
		echo "\t  Renormalization scale muR = $xmur * MH/2\n"
	    else
		echo "\t  Renormalization scale muR = $xmur * $mur0 GeV\n"
	    fi
	fi
    else
	if [ $muf_flag == 0 ]
	then
	    if [ $mur_flag == 0 ]
	    then
		echo "\t  Central scales muF0 = muR0 = MH/2\n"
	    else
		echo "\t  Central scales muF0 = MH/2, muR0 = $mur0 GeV\n"
	    fi
	else
	    if [ $mur_flag == 0 ]
	    then
		echo "\t  Central scales muF0 = $muf0 GeV, muR0 = MH/2\n"
	    else
		echo "\t  Central scales muF0 = $muf0 GeV, muR0 = $mur0 GeV\n"
	    fi
	fi
    fi
    if [ $mtscheme -eq 0 ]
    then
	echo "\t  The calculation uses the OS scheme for the top-quark"
    else
	echo "\t  The calculation uses the MSbar scheme for the top-quark"
    fi
    echo "\tNow calculating for inclusive ggH process in the Born-improved HTL...\n"
    if [ $seven -eq 0 ]
    then
	${maindir}/subprogs/run_ggh $lattice $seed $qcd $collider $energy $xmuf $muf0 $xmur $mur0 $muf_flag $mur_flag $pdfset $pdfnum $parameters $scale
    else
	${maindir}/subprogs/run_ggh $lattice $seed $qcd $collider $energy 1.0 $muf0 $xmur $mur0 $muf_flag $mur_flag $pdfset $pdfnum $parameters --scale
	${maindir}/subprogs/run_ggh $lattice $seed $qcd $collider $energy 0.5 $muf0 $xmur $mur0 $muf_flag $mur_flag $pdfset $pdfnum $parameters --scale
	${maindir}/subprogs/run_ggh $lattice $seed $qcd $collider $energy 2.0 $muf0 $xmur $mur0 $muf_flag $mur_flag $pdfset $pdfnum $parameters --scale
    fi
else
    echo "\tYou have selected a process which does not exist (yet)! Program will exit..."
fi

if [ $seven -eq 1 ]
then
#    energy2=$(echo $energy | bc -l | sed '/\./ s/\.\{0,1\}0\{1,\}$//')
    energy2=$(echo $energy | sed '/\./ s/\.\{0,1\}0\{1,\}$//')
    if [ $collider -eq 0 ]
    then
	if [ $type -lt 3 ]
	then
	    q2=$(echo $q | sed '/\./ s/\.\{0,1\}0\{1,\}$//')
	    filetest1=${proctag}_pp_${energy2}tev_q${q2}_pdf${pdfnum}_muf1.txt
	    filetest0=${proctag}_pp_${energy2}tev_q${q2}_pdf${pdfnum}_muf0.5.txt
	    filetest2=${proctag}_pp_${energy2}tev_q${q2}_pdf${pdfnum}_muf2.txt
	else
	    filetest1=${proctag}_pp_${energy2}tev_pdf${pdfnum}_muf1.txt
	    filetest0=${proctag}_pp_${energy2}tev_pdf${pdfnum}_muf0.5.txt
	    filetest2=${proctag}_pp_${energy2}tev_pdf${pdfnum}_muf2.txt
	fi
    else
	if [ $type -lt 3 ]
	then
	    q2=$(echo $q | sed '/\./ s/\.\{0,1\}0\{1,\}$//')
	    filetest1=${proctag}_ppbar_${energy2}tev_q${q2}_pdf${pdfnum}_muf1.txt
	    filetest0=${proctag}_ppbar_${energy2}tev_q${q2}_pdf${pdfnum}_muf0.5.txt
	    filetest2=${proctag}_ppbar_${energy2}tev_q${q2}_pdf${pdfnum}_muf2.txt
	else
	    filetest1=${proctag}_ppbar_${energy2}tev_pdf${pdfnum}_muf1.txt
	    filetest0=${proctag}_ppbar_${energy2}tev_pdf${pdfnum}_muf0.5.txt
	    filetest2=${proctag}_ppbar_${energy2}tev_pdf${pdfnum}_muf2.txt
	fi
    fi
	
    let lotag="4+$qcd"
    central_lo="$(cut -d ' ' -f 3 <<< $(grep "1.000\t1.000" ${filetest1}))"
    error_lo="$(cut -d ' ' -f $lotag <<< $(grep "1.000\t1.000" ${filetest1}))"
    min_lo=$central_lo
    max_lo=$central_lo
    test_lo="$(cut -d ' ' -f 3 <<< $(grep "0.500\t1.000" ${filetest1}))"
    if [ 1 -eq "$(echo "$test_lo < $min_lo" | bc)" ]
    then
	min_lo=$test_lo
    fi
    if [ 1 -eq "$(echo "$test_lo > $max_lo" | bc)" ]
    then
	max_lo=$test_lo
    fi
    test_lo="$(cut -d ' ' -f 3 <<< $(grep "2.000\t1.000" ${filetest1}))"
    if [ 1 -eq "$(echo "$test_lo < $min_lo" | bc)" ]
    then
	min_lo=$test_lo
    fi
    if [ 1 -eq "$(echo "$test_lo > $max_lo" | bc)" ]
    then
	max_lo=$test_lo
    fi
    test_lo="$(cut -d ' ' -f 3 <<< $(grep "0.500\t0.500" ${filetest0}))"
    if [ 1 -eq "$(echo "$test_lo < $min_lo" | bc)" ]
    then
	min_lo=$test_lo
    fi
    if [ 1 -eq "$(echo "$test_lo > $max_lo" | bc)" ]
    then
	max_lo=$test_lo
    fi
    test_lo="$(cut -d ' ' -f 3 <<< $(grep "1.000\t0.500" ${filetest0}))"
    if [ 1 -eq "$(echo "$test_lo < $min_lo" | bc)" ]
    then
	min_lo=$test_lo
    fi
    if [ 1 -eq "$(echo "$test_lo > $max_lo" | bc)" ]
    then
	max_lo=$test_lo
    fi
    test_lo="$(cut -d ' ' -f 3 <<< $(grep "1.500\t2.000" ${filetest2}))"
    if [ 1 -eq "$(echo "$test_lo < $min_lo" | bc)" ]
    then
	min_lo=$test_lo
    fi
    if [ 1 -eq "$(echo "$test_lo > $max_lo" | bc)" ]
    then
	max_lo=$test_lo
    fi
    test_lo="$(cut -d ' ' -f 3 <<< $(grep "2.000\t2.000" ${filetest2}))"
    if [ 1 -eq "$(echo "$test_lo < $min_lo" | bc)" ]
    then
	min_lo=$test_lo
    fi
    if [ 1 -eq "$(echo "$test_lo > $max_lo" | bc)" ]
    then
	max_lo=$test_lo
    fi

    percent_max_lo=$(awk -v a="$central_lo" -v b="$max_lo" 'BEGIN {PREC = "double"; print 100*(b-a)/a}')
    percent_min_lo=$(awk -v a="$central_lo" -v b="$min_lo" 'BEGIN {PREC = "double"; print 100*(b-a)/a}')
    echo "\nxs_LO    = $central_lo +- $error_lo (num) pb +$percent_max_lo% / $percent_min_lo% (7-point scale uncertainty)"

    if [ $qcd -ge 1 ]
    then
	let nlotag="5+$qcd"
	central_nlo="$(cut -d ' ' -f 4 <<< $(grep "1.000\t1.000" ${filetest1}))"
	error_nlo="$(cut -d ' ' -f $nlotag <<< $(grep "1.000\t1.000" ${filetest1}))"
	min_nlo=$central_nlo
	max_nlo=$central_nlo
	test_nlo="$(cut -d ' ' -f 4 <<< $(grep "0.500\t1.000" ${filetest1}))"
	if [ 1 -eq "$(echo "$test_nlo < $min_nlo" | bc)" ]
	then
	    min_nlo=$test_nlo
	fi
	if [ 1 -eq "$(echo "$test_nlo > $max_nlo" | bc)" ]
	then
	    max_nlo=$test_nlo
	fi
	test_nlo="$(cut -d ' ' -f 4 <<< $(grep "2.000\t1.000" ${filetest1}))"
	if [ 1 -eq "$(echo "$test_nlo < $min_nlo" | bc)" ]
	then
	    min_nlo=$test_nlo
	fi
	if [ 1 -eq "$(echo "$test_nlo > $max_nlo" | bc)" ]
	then
	    max_nlo=$test_nlo
	fi
	test_nlo="$(cut -d ' ' -f 4 <<< $(grep "0.500\t0.500" ${filetest0}))"
	if [ 1 -eq "$(echo "$test_nlo < $min_nlo" | bc)" ]
	then
	    min_nlo=$test_nlo
	fi
	if [ 1 -eq "$(echo "$test_nlo > $max_nlo" | bc)" ]
	then
	    max_nlo=$test_nlo
	fi
	test_nlo="$(cut -d ' ' -f 4 <<< $(grep "1.000\t0.500" ${filetest0}))"
	if [ 1 -eq "$(echo "$test_nlo < $min_nlo" | bc)" ]
	then
	    min_nlo=$test_nlo
	fi
	if [ 1 -eq "$(echo "$test_nlo > $max_nlo" | bc)" ]
	then
	    max_nlo=$test_nlo
	fi
	test_nlo="$(cut -d ' ' -f 4 <<< $(grep "1.500\t2.000" ${filetest2}))"
	if [ 1 -eq "$(echo "$test_nlo < $min_nlo" | bc)" ]
	then
	    min_nlo=$test_nlo
	fi
	if [ 1 -eq "$(echo "$test_nlo > $max_nlo" | bc)" ]
	then
	    max_nlo=$test_nlo
	fi
	test_nlo="$(cut -d ' ' -f 4 <<< $(grep "2.000\t2.000" ${filetest2}))"
	if [ 1 -eq "$(echo "$test_nlo < $min_nlo" | bc)" ]
	then
	    min_nlo=$test_nlo
	fi
	if [ 1 -eq "$(echo "$test_nlo > $max_nlo" | bc)" ]
	then
	    max_nlo=$test_nlo
	fi

	percent_max_nlo=$(awk -v a="$central_nlo" -v b="$max_nlo" 'BEGIN {PREC = "double"; print 100*(b-a)/a}')
	percent_min_nlo=$(awk -v a="$central_nlo" -v b="$min_nlo" 'BEGIN {PREC = "double"; print 100*(b-a)/a}')
	echo "xs_NLO   = $central_nlo +- $error_nlo (num) pb +$percent_max_nlo% / $percent_min_nlo% (7-point scale uncertainty)"
	if [ $qcd -ge 2 ]
	then
	    let nnlotag="6+$qcd"
	    central_nnlo="$(cut -d ' ' -f 5 <<< $(grep "1.000\t1.000" ${filetest1}))"
	    error_nnlo="$(cut -d ' ' -f $nnlotag <<< $(grep "1.000\t1.000" ${filetest1}))"
	    min_nnlo=$central_nnlo
	    max_nnlo=$central_nnlo
	    test_nnlo="$(cut -d ' ' -f 5 <<< $(grep "0.500\t1.000" ${filetest1}))"
	    if [ 1 -eq "$(echo "$test_nnlo < $min_nnlo" | bc)" ]
	    then
		min_nnlo=$test_nnlo
	    fi
	    if [ 1 -eq "$(echo "$test_nnlo > $max_nnlo" | bc)" ]
	    then
		max_nnlo=$test_nnlo
	    fi
	    test_nnlo="$(cut -d ' ' -f 5 <<< $(grep "2.000\t1.000" ${filetest1}))"
	    if [ 1 -eq "$(echo "$test_nnlo < $min_nnlo" | bc)" ]
	    then
		min_nnlo=$test_nnlo
	    fi
	    if [ 1 -eq "$(echo "$test_nnlo > $max_nnlo" | bc)" ]
	    then
		max_nnlo=$test_nnlo
	    fi
	    test_nnlo="$(cut -d ' ' -f 5 <<< $(grep "0.500\t0.500" ${filetest0}))"
	    if [ 1 -eq "$(echo "$test_nnlo < $min_nnlo" | bc)" ]
	    then
		min_nnlo=$test_nnlo
	    fi
	    if [ 1 -eq "$(echo "$test_nnlo > $max_nnlo" | bc)" ]
	    then
		max_nnlo=$test_nnlo
	    fi
	    test_nnlo="$(cut -d ' ' -f 5 <<< $(grep "1.000\t0.500" ${filetest0}))"
	    if [ 1 -eq "$(echo "$test_nnlo < $min_nnlo" | bc)" ]
	    then
		min_nnlo=$test_nnlo
	    fi
	    if [ 1 -eq "$(echo "$test_nnlo > $max_nnlo" | bc)" ]
	    then
		max_nnlo=$test_nnlo
	    fi
	    test_nnlo="$(cut -d ' ' -f 5 <<< $(grep "1.500\t2.000" ${filetest2}))"
	    if [ 1 -eq "$(echo "$test_nnlo < $min_nnlo" | bc)" ]
	    then
		min_nnlo=$test_nnlo
	    fi
	    if [ 1 -eq "$(echo "$test_nnlo > $max_nnlo" | bc)" ]
	    then
		max_nnlo=$test_nnlo
	    fi
	    test_nnlo="$(cut -d ' ' -f 5 <<< $(grep "2.000\t2.000" ${filetest2}))"
	    if [ 1 -eq "$(echo "$test_nnlo < $min_nnlo" | bc)" ]
	    then
		min_nnlo=$test_nnlo
	    fi
	    if [ 1 -eq "$(echo "$test_nnlo > $max_nnlo" | bc)" ]
	    then
		max_nnlo=$test_nnlo
	    fi

	    percent_max_nnlo=$(awk -v a="$central_nnlo" -v b="$max_nnlo" 'BEGIN {PREC = "double"; print 100*(b-a)/a}')
	    percent_min_nnlo=$(awk -v a="$central_nnlo" -v b="$min_nnlo" 'BEGIN {PREC = "double"; print 100*(b-a)/a}')
	    echo "xs_NNLO  = $central_nnlo +- $error_nnlo (num) pb +$percent_max_nnlo% / $percent_min_nnlo% (7-point scale uncertainty)"
	    if [ $qcd -eq 3 ]
	    then
		central_n3lo="$(cut -d ' ' -f 6 <<< $(grep "1.000\t1.000" ${filetest1}))"
		error_n3lo="$(cut -d ' ' -f 10 <<< $(grep "1.000\t1.000" ${filetest1}))"
		min_n3lo=$central_n3lo
		max_n3lo=$central_n3lo
		test_n3lo="$(cut -d ' ' -f 6 <<< $(grep "0.500\t1.000" ${filetest1}))"
		if [ 1 -eq "$(echo "$test_n3lo < $min_n3lo" | bc)" ]
		then
		    min_n3lo=$test_n3lo
		fi
		if [ 1 -eq "$(echo "$test_n3lo > $max_n3lo" | bc)" ]
		then
		    max_n3lo=$test_n3lo
		fi
		test_n3lo="$(cut -d ' ' -f 6 <<< $(grep "2.000\t1.000" ${filetest1}))"
		if [ 1 -eq "$(echo "$test_n3lo < $min_n3lo" | bc)" ]
		then
		    min_n3lo=$test_n3lo
		fi
		if [ 1 -eq "$(echo "$test_n3lo > $max_n3lo" | bc)" ]
		then
		    max_n3lo=$test_n3lo
		fi
		test_n3lo="$(cut -d ' ' -f 6 <<< $(grep "0.500\t0.500" ${filetest0}))"
		if [ 1 -eq "$(echo "$test_n3lo < $min_n3lo" | bc)" ]
		then
		    min_n3lo=$test_n3lo
		fi
		if [ 1 -eq "$(echo "$test_n3lo > $max_n3lo" | bc)" ]
		then
		    max_n3lo=$test_n3lo
		fi
		test_n3lo="$(cut -d ' ' -f 6 <<< $(grep "1.000\t0.500" ${filetest0}))"
		if [ 1 -eq "$(echo "$test_n3lo < $min_n3lo" | bc)" ]
		then
		    min_n3lo=$test_n3lo
		fi
		if [ 1 -eq "$(echo "$test_n3lo > $max_n3lo" | bc)" ]
		then
		    max_n3lo=$test_n3lo
		fi
		test_n3lo="$(cut -d ' ' -f 6 <<< $(grep "1.500\t2.000" ${filetest2}))"
		if [ 1 -eq "$(echo "$test_n3lo < $min_n3lo" | bc)" ]
		then
		    min_n3lo=$test_n3lo
		fi
		if [ 1 -eq "$(echo "$test_n3lo > $max_n3lo" | bc)" ]
		then
		    max_n3lo=$test_n3lo
		fi
		test_n3lo="$(cut -d ' ' -f 6 <<< $(grep "2.000\t2.000" ${filetest2}))"
		if [ 1 -eq "$(echo "$test_n3lo < $min_n3lo" | bc)" ]
		then
		    min_n3lo=$test_n3lo
		fi
		if [ 1 -eq "$(echo "$test_n3lo > $max_n3lo" | bc)" ]
		then
		    max_n3lo=$test_n3lo
		fi

		percent_max_n3lo=$(awk -v a="$central_n3lo" -v b="$max_n3lo" 'BEGIN {PREC = "double"; print 100*(b-a)/a}')
		percent_min_n3lo=$(awk -v a="$central_n3lo" -v b="$min_n3lo" 'BEGIN {PREC = "double"; print 100*(b-a)/a}')
		echo "xs_N3LO  = $central_n3lo +- $error_n3lo (num) pb +$percent_max_n3lo% / $percent_min_n3lo% (7-point scale uncertainty)"
	    fi
	fi
    fi
else
    energy2=$(echo $energy | sed '/\./ s/\.\{0,1\}0\{1,\}$//')
    xmuf2=$(echo $xmuf | sed '/\./ s/\.\{0,1\}0\{1,\}$//')
    xmuf3=$(echo "$xmuf" | cut -c1-5)
    if [ -z ${scale} ]
    then
	xmur2=$(echo $xmur | sed '/\./ s/\.\{0,1\}0\{1,\}$//')
	xmur3=$(echo "$xmur" | cut -c1-5)
	if [ $collider -eq 0 ]
	then
	    if [ $type -lt 3 ]
	    then
		fileoutput=${proctag}_pp_${energy2}tev_q${q2}_pdf${pdfnum}_muf${xmuf2}_mur${xmur2}.txt
	    else
		fileoutput=${proctag}_pp_${energy2}tev_pdf${pdfnum}_muf${xmuf2}_mur${xmur2}.txt
	    fi
	else
	    if [ $type -lt 3 ]
	    then
		fileoutput=${proctag}_ppbar_${energy2}tev_q${q2}_pdf${pdfnum}_muf${xmuf2}_mur${xmur2}.txt
	    else
		fileoutput=${proctag}_ppbar_${energy2}tev_pdf${pdfnum}_muf${xmuf2}_mur${xmur2}.txt
	    fi
	fi
    else
	if [ $collider -eq 0 ]
	then
	    if [ $type -lt 3 ]
	    then
		fileoutput=${proctag}_pp_${energy2}tev_q${q2}_pdf${pdfnum}_muf${xmuf2}.txt
	    else
		fileoutput=${proctag}_pp_${energy2}tev_pdf${pdfnum}_muf${xmuf2}.txt
	    fi
	else
	    if [ $type -lt 3 ]
	    then
		fileoutput=${proctag}_ppbar_${energy2}tev_q${q2}_pdf${pdfnum}_muf${xmuf2}.txt
	    else
		fileoutput=${proctag}_ppbar_${energy2}tev_pdf${pdfnum}_muf${xmuf2}.txt
	    fi
	fi
    fi
    let lotag="4+$qcd"
    if [ -z ${scale} ]
    then
	central_lo="$(cut -d ' ' -f 3 <<< $(grep "${xmur3}" ${fileoutput}))"
	error_lo="$(cut -d ' ' -f $lotag <<< $(grep "${xmur3}" ${fileoutput}))"
	echo "\nxs_LO(xmur=$xmur,xmuf=$xmuf)    = $central_lo +- $error_lo (num) pb"
    else
	central_lo="$(cut -d ' ' -f 3 <<< $(grep "1.000\t${xmuf3}" ${fileoutput}))"
	error_lo="$(cut -d ' ' -f $lotag <<< $(grep "1.000\t${xmuf3}" ${fileoutput}))"
	echo "\nxs_LO(xmur=1.0,xmuf=$xmuf)    = $central_lo +- $error_lo (num) pb"
    fi
    if [ $qcd -ge 1 ]
    then
	let nlotag="5+$qcd"
	if [ -z ${scale} ]
	then
	    central_nlo="$(cut -d ' ' -f 4 <<< $(grep "${xmur3}" ${fileoutput}))"
	    error_nlo="$(cut -d ' ' -f $nlotag <<< $(grep "${xmur3}" ${fileoutput}))"
	    echo "xs_NLO(xmur=$xmur,xmuf=$xmuf)   = $central_nlo +- $error_nlo (num) pb"
	else
	    central_nlo="$(cut -d ' ' -f 4 <<< $(grep "1.000\t${xmuf3}" ${fileoutput}))"
	    error_nlo="$(cut -d ' ' -f $nlotag <<< $(grep "1.000\t${xmuf3}" ${fileoutput}))"
	    echo "xs_NLO(xmur=1.0,xmuf=$xmuf)   = $central_nlo +- $error_nlo (num) pb"
	fi
	if [ $qcd -ge 2 ]
	then
	    let nnlotag="6+$qcd"
	    if [ -z ${scale} ]
	    then
		central_nnlo="$(cut -d ' ' -f 5 <<< $(grep "${xmur3}" ${fileoutput}))"
		error_nnlo="$(cut -d ' ' -f $nnlotag <<< $(grep "${xmur3}" ${fileoutput}))"
		echo "xs_NNLO(xmur=$xmur,xmuf=$xmuf)  = $central_nnlo +- $error_nnlo (num) pb"
	    else
		central_nnlo="$(cut -d ' ' -f 5 <<< $(grep "1.000\t${xmuf3}" ${fileoutput}))"
		error_nnlo="$(cut -d ' ' -f $nnlotag <<< $(grep "1.000\t${xmuf3}" ${fileoutput}))"
		echo "xs_NNLO(xmur=1.0,xmuf=$xmuf)  = $central_nnlo +- $error_nnlo (num) pb"
	    fi
	    if [ $qcd -eq 3 ]
	    then
		if [ -z ${scale} ]
		then
		    central_n3lo="$(cut -d ' ' -f 6 <<< $(grep "${xmur3}" ${fileoutput}))"
		    error_n3lo="$(cut -d ' ' -f 10 <<< $(grep "${xmur3}" ${fileoutput}))"
		    echo "xs_N3LO(xmur=$xmur,xmuf=$xmuf)  = $central_n3lo +- $error_n3lo (num) pb"
		else
		    central_n3lo="$(cut -d ' ' -f 6 <<< $(grep "1.000\t${xmuf3}" ${fileoutput}))"
		    error_n3lo="$(cut -d ' ' -f 10 <<< $(grep "1.000\t${xmuf3}" ${fileoutput}))"
		    echo "xs_N3LO(xmur=1.0,xmuf=$xmuf)  = $central_n3lo +- $error_n3lo (num) pb"
		fi
	    fi
	fi
    fi
fi

if [ $seven -eq 1 ]
then
    rm $filetest1 && rm $filetest0 && rm $filetest2
fi   

echo "\n\tThanks for using our program!\n"
